USE [SCAMS]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Bureau]') AND type in (N'U'))
BEGIN
        DROP TABLE [dbo].Bureau
END


CREATE TABLE [Bureau] (
	BureauID INT IDENTITY(1,1) NOT NULL,
	BureauName varchar(50) NOT NULL,
	Code varchar(2) NOT NULL,
	FLAIRName varchar(50) NOT NULL,
	CONSTRAINT [PK_BureauID] PRIMARY KEY CLUSTERED 
	(
		BureauID ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
