USE [SCAMS]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ObjectCode]') AND type in (N'U'))
BEGIN
        DROP TABLE [dbo].ObjectCode
END


CREATE TABLE [ObjectCode] (
	ObjectCodeID INT IDENTITY(1,1) NOT NULL,
	ObjectCodeDescription varchar(2) NOT NULL,
	CONSTRAINT [PK_ObjectCodeID] PRIMARY KEY CLUSTERED 
	(
		ObjectCodeID ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
